services:
  frontend:
    build:
      context: ./nextjs-app
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build:
      context: web
      dockerfile: Dockerfile
    ports:
      - "5000:80"
