// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using web.Data;

#nullable disable

namespace web.Migrations
{
    [DbContext(typeof(WebContext))]
    [Migration("20240319073700_MoreFields")]
    partial class MoreFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.2");

            modelBuilder.Entity("Approval", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BidMoney")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CSRS")
                        .HasColumnType("TEXT");

                    b.Property<string>("ComplianceStatus")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateOfApprovalRenewal")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateOfExpiry")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateOfFiling")
                        .HasColumnType("TEXT");

                    b.Property<string>("District")
                        .HasColumnType("TEXT");

                    b.Property<int>("FinancialImpact")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Mineral")
                        .HasColumnType("TEXT");

                    b.Property<string>("NatureOfCase")
                        .HasColumnType("TEXT");

                    b.Property<string>("Remarks")
                        .HasColumnType("TEXT");

                    b.Property<int>("ReservePrice")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SIRConducted")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT");

                    b.Property<string>("TitleOfLease")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Approval");
                });
#pragma warning restore 612, 618
        }
    }
}
